-- 코드를 입력하세요
SELECT C.CAR_ID, 
       C.CAR_TYPE,
       C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100 AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
           ON C.CAR_TYPE = P.CAR_TYPE AND
              P.DURATION_TYPE = '30일 이상'
WHERE CAR_ID NOT IN (SELECT CAR_ID
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                     WHERE (START_DATE < TO_DATE('20221101', 'YYYYMMDD') AND END_DATE > TO_DATE('20221130', 'YYYYMMDD')) OR
                           START_DATE BETWEEN TO_DATE('20221101', 'YYYYMMDD') AND TO_DATE('20221130', 'YYYYMMDD') OR
                           END_DATE BETWEEN TO_DATE('20221101', 'YYYYMMDD') AND TO_DATE('20221130', 'YYYYMMDD')) AND
      C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100 BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;