-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
INNER JOIN ANIMAL_OUTS O
           ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SUBSTR(I.SEX_UPON_INTAKE, 1, INSTR(I.SEX_UPON_INTAKE, ' ') - 1) = 'Intact' AND
      SUBSTR(O.SEX_UPON_OUTCOME, 1, INSTR(O.SEX_UPON_OUTCOME, ' ') - 1) IN ('Spayed', 'Neutered')
ORDER BY I.ANIMAL_ID ASC;