-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM S.SALES_DATE) AS YEAR,
       EXTRACT(MONTH FROM S.SALES_DATE) AS MONTH,
       I.GENDER,
       COUNT(DISTINCT I.USER_ID) AS USERS
FROM ONLINE_SALE S
INNER JOIN USER_INFO I
           ON S.USER_ID = I.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM S.SALES_DATE),
         EXTRACT(MONTH FROM S.SALES_DATE),
         I.GENDER
ORDER BY YEAR ASC,
         MONTH ASC,
         GENDER ASC;