-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE * O.TOTAL_AMOUNT) AS TOTAL_SALES
FROM (SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
      FROM FOOD_ORDER
      WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
      GROUP BY PRODUCT_ID) O
INNER JOIN FOOD_PRODUCT P
           ON O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC,
         P.PRODUCT_ID ASC;
            
