-- 코드를 입력하세요
SELECT I.HISTORY_ID, 
       I.DAYS * I.DAILY_FEE * (100 - NVL(P.DISCOUNT_RATE, 0)) / 100 AS FEE
FROM (SELECT C.CAR_TYPE, C.DAILY_FEE, H.HISTORY_ID, H.END_DATE - H.START_DATE + 1 AS DAYS
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
      INNER JOIN CAR_RENTAL_COMPANY_CAR C
                 ON H.CAR_ID = C.CAR_ID
      WHERE C.CAR_TYPE = '트럭') I
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
                ON I.CAR_TYPE = P.CAR_TYPE AND
                   ((DAYS >= 90 AND P.DURATION_TYPE = '90일 이상') OR
                   (DAYS BETWEEN 30 AND 89 AND P.DURATION_TYPE = '30일 이상') OR
                   (DAYS BETWEEN 7 AND 29 AND P.DURATION_TYPE = '7일 이상'))
ORDER BY FEE DESC, I.HISTORY_ID DESC;