-- 코드를 입력하세요
SELECT FLAVOR
FROM (SELECT H.FLAVOR, H.TOTAL_ORDER + SUM(J.TOTAL_ORDER) AS TOTAL
      FROM FIRST_HALF H
      LEFT OUTER JOIN JULY J
                      ON H.FLAVOR = J.FLAVOR
      GROUP BY H.FLAVOR, H.TOTAL_ORDER
      ORDER BY TOTAL DESC)
WHERE ROWNUM <= 3;