-- 코드를 입력하세요
SELECT H.HOUR, COUNT(O.ANIMAL_ID) AS COUNT
FROM (SELECT LEVEL - 1 AS HOUR 
      FROM DUAL
      CONNECT BY LEVEL BETWEEN 1 AND 24) H
LEFT OUTER JOIN ANIMAL_OUTS O
                ON EXTRACT(HOUR from CAST(DATETIME AS TIMESTAMP)) = H.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR ASC;