-- 코드를 입력하세요
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM (SELECT MEMBER_ID
      FROM REST_REVIEW
      GROUP BY MEMBER_ID
      ORDER BY COUNT(*) DESC
      FETCH FIRST 1 ROWS ONLY) M
INNER JOIN MEMBER_PROFILE P
           ON M.MEMBER_ID = P.MEMBER_ID
INNER JOIN REST_REVIEW R
           ON M.MEMBER_ID = R.MEMBER_ID
ORDER BY R.REVIEW_DATE ASC, REVIEW_TEXT ASC;