-- 코드를 입력하세요
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE START_DATE >= TO_DATE('20220801', 'YYYYMMDD') AND 
                       START_DATE < TO_DATE('20221101', 'YYYYMMDD')
                 GROUP BY CAR_ID
                          HAVING COUNT(*) >= 5) AND
      START_DATE >= TO_DATE('20220801', 'YYYYMMDD') AND 
      START_DATE < TO_DATE('20221101', 'YYYYMMDD')
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
ORDER BY MONTH ASC,
         CAR_ID DESC;